[package]
name = "direct-consumer"
version = "0.1.0"
edition = "2024"

[dependencies]
log = "0.4"
env_logger = "0.11"
lapin = "2.5.3"
tokio = { version = "1", features = ["full"] }
futures-lite = "^2.0"